---
title: "Sogndal_Data"
format: html
editor: visual
---

```{r}
library(dplyr)
library(readr)
library(data.table)
library(tidyverse)
library(ggplot2)
library(lubridate)
```

```{r}
##Copied R Code that reates the function calc_soil_moist for transfering the raw soil moisture values from the field into TMS form
calc_soil_moist <- function(rawsoilmoist, soil_temp, soilclass){
  # creating df with parameters for each soil type, as specified from TOMST info
  soilclass.df <- tibble(
    soil = c("sand", "loamy_sand_A", "loamy_sand_B", "sandy_loam_A", "sandy_loam_B", "loam", "silt_loam", "peat"),
    a = c(-3E-9, -1.9e-8, -2.3e-8, -3.8e-8, -9e-10, -5.1e-8, 1.7e-8, 1.23e-7),
    b = c(1.61192e-4, 2.6561e-4, 2.82473e-4, 3.39449e-4, 2.61847e-4, 3.97984e-4, 1.18119e-4, 1.44644e-4),
    c = c(-0.109956505, -0.154089291, -0.167211156, -0.214921782, -0.158618303, 0.291046437, -0.101168511, 0.202927906),
    AirCalib = rep(57.64530756, 8), # a constant across all soil types, don't know exactly what this does
    AirPuls = rep(56.88867311, 8), # a constant across all soil types, don't know exactly what this does
    DilVol = rep(-59.72975311, 8) # a constant across all soil types, don't know exactly what this does
  )
  #filtering soilclass.df based on which soilclass was entered in the function
  soilclass.df <- soilclass.df |>
    filter(
      soil == {{soilclass}}
    )
  #calculating the volumetric soil moisture with the parameters corresponding to the soil class and the raw soil moisture from the logger
  volmoist = with(soilclass.df, {(a * rawsoilmoist^2) + (b * rawsoilmoist) + c})
  #temperature correction
  temp_ref <- 24
  delta_air <- 1.91132689118083
  delta_water <- 0.64108
  delta_dil <- -1.270246891 # this is delta-water - delta_air
  # we don't know what this does or what the variables do, but the result is the same as in excel
  temp_corr <- rawsoilmoist + ((temp_ref-soil_temp) * (delta_air + delta_dil * volmoist))
  # volumetric soil moisture with temperatue correction
  volmoistcorr <- with(soilclass.df,
                       ifelse(rawsoilmoist>AirCalib,
                              (temp_corr+AirPuls+DilVol*volmoist)^2*a+(temp_corr+AirPuls+DilVol*volmoist)*b+c,
                              NA))
  volmoistcorr
  # return(volmoist) #let's just use the soil moisture without temperature correction for now
}
```

```{r}
##General introductory code formatting date into date form, separatign date and time, editing column names, removing unfilled/unimportant columns, and adding habitat and species titles
library(dplyr)
library(readr)
library(data.table)
library(tidyverse)
csv_files<-list.files(path = "/Users/samuelking/Downloads/Sogndal_TOMS_Data", pattern = "*.csv", full.names = TRUE)

combined_data <- rbindlist(lapply(csv_files, function(file) {fread(file)[, source_file := basename(file)]}))

combined_data <- combined_data %>% 
  separate(V2, into = c("date", "time"), sep = " ")

combined_data <- combined_data %>%mutate(date = as.Date(date, format = "%Y.%m.%d"))

filtered_data <- combined_data %>% filter(date >= as.Date("2023-06-26"))

filtered_data<- filtered_data %>% rename (Temp_1 = V4, Temp_2 = V5, Temp_3 = V6)

filtered_data<- filtered_data %>% select(-V1)

filtered_data$source_file<- sub("data_", "", filtered_data$source_file)

filtered_data$source_file<- sub(".csv", "", filtered_data$source_file)

filtered_data$source_file<- sub("_2025_05_22_0", "", filtered_data$source_file)

filtered_data$source_file<- sub("_2025_05_22_1", "", filtered_data$source_file)

filtered_data<- filtered_data %>% rename (Logger_ID = source_file)

further_consolidated<-filtered_data %>% select(-V9)

further_consolidated<-further_consolidated %>% select(-V10)

further_consolidated<-further_consolidated %>% select(-V3)

further_consolidated<-further_consolidated %>% select(-V8)

further_consolidated<- further_consolidated %>% rename (SoilMoist_Raw = V7)

open_data<- further_consolidated%>%
  mutate(habitat=case_when(Logger_ID=="94194604"~"Open", 
                           Logger_ID=="94195240"~"Open",
                           Logger_ID=="94195263"~"Open",
                           Logger_ID=="94195264"~"Open",
                           Logger_ID=="94195271"~"Open",
                           Logger_ID=="94200491"~"Open",
                           Logger_ID=="94200498"~"Open",
                           Logger_ID=="95221001"~"Open",
                           Logger_ID=="95221019"~"Open",
                           Logger_ID=="95221029"~"Open",
                           Logger_ID=="95221032"~"Open",
                           Logger_ID=="95221034"~"Open",
                           Logger_ID=="95221036"~"Open",
                           Logger_ID=="95221040"~"Open",
                           Logger_ID=="95221041"~"Open",
                           Logger_ID=="95221054"~"Open",
                           Logger_ID=="95221056"~"Open",
                           Logger_ID=="95221058"~"Open",
                           Logger_ID=="95221060"~"Open",
                           Logger_ID=="95221192"~"Open",
                           Logger_ID=="95221011"~"Forest",
                           Logger_ID=="95221049"~"Forest",
                           Logger_ID=="95221043"~"Forest",
                           Logger_ID=="95221026"~"Forest",
                           Logger_ID=="95221194"~"Forest",
                           Logger_ID=="95221028"~"Forest",
                           Logger_ID=="94195218"~"Forest",
                           Logger_ID=="95221059"~"Forest",
                           Logger_ID=="95221042"~"Forest",
                           Logger_ID=="95221048"~"Forest",
                           Logger_ID=="94195268"~"Forest",
                           Logger_ID=="95221047"~"Forest",
                           Logger_ID=="95221022"~"Forest",
                           Logger_ID=="95221005"~"Forest",
                           Logger_ID=="94195201"~"Forest",
                           Logger_ID=="94195259"~"Forest",
                           Logger_ID=="95221018"~"Forest",
                           Logger_ID=="95221025"~"Forest",
                           Logger_ID=="94195232"~"Forest",
                           Logger_ID=="95221015"~"Forest",
                           TRUE~"N/A"))

open_data<- open_data%>%
  mutate(species=case_when(Logger_ID=="94194604"~"Empetrum nigrum", 
                           Logger_ID=="94195240"~"Vaccinium vitis-idaea",
                           Logger_ID=="94195263"~"Vaccinium vitis-idaea",
                           Logger_ID=="94195264"~"Calluna vulgaris",
                           Logger_ID=="94195271"~"Vaccinium vitis-idaea",
                           Logger_ID=="94200491"~"Calluna vulgaris",
                           Logger_ID=="94200498"~"Vaccinium vitis-idaea",
                           Logger_ID=="95221001"~"Vaccinium myrtillus",
                           Logger_ID=="95221019"~"Calluna vulgaris",
                           Logger_ID=="95221029"~"Empetrum nigrum",
                           Logger_ID=="95221032"~"Vaccinium myrtillus",
                           Logger_ID=="95221034"~"Empetrum nigrum",
                           Logger_ID=="95221036"~"Vaccinium myrtillus",
                           Logger_ID=="95221040"~"Calluna vulgaris",
                           Logger_ID=="95221041"~"Vaccinium myrtillus",
                           Logger_ID=="95221054"~"Empetrum nigrum",
                           Logger_ID=="95221056"~"Vaccinium vitis-idaea",
                           Logger_ID=="95221058"~"Calluna vulgaris",
                           Logger_ID=="95221060"~"Empetrum nigrum",
                           Logger_ID=="95221192"~"Vaccinium myrtillus",
                           Logger_ID=="95221011"~"Calluna vulgaris",
                           Logger_ID=="95221049"~"Calluna vulgaris",
                           Logger_ID=="95221043"~"Calluna vulgaris",
                           Logger_ID=="95221026"~"Calluna vulgaris",
                           Logger_ID=="95221059"~"Calluna vulgaris",
                           Logger_ID=="95221028"~"Empetrum nigrum",
                           Logger_ID=="94195218"~"Empetrum nigrum",
                           Logger_ID=="95221194"~"Empetrum nigrum",
                           Logger_ID=="95221042"~"Vaccinium vitis-idaea",
                           Logger_ID=="95221048"~"Vaccinium vitis-idaea",
                           Logger_ID=="94195268"~"Vaccinium myrtillus",
                           Logger_ID=="95221047"~"Vaccinium myrtillus",
                           Logger_ID=="95221022"~"Empetrum nigrum",
                           Logger_ID=="95221005"~"Vaccinium myrtillus",
                           Logger_ID=="94195201"~"Vaccinium myrtillus",
                           Logger_ID=="94195259"~"Empetrum nigrum",
                           Logger_ID=="95221018"~"Vaccinium vitis-idaea",
                           Logger_ID=="95221025"~"Vaccinium myrtillus",
                           Logger_ID=="94195232"~"Vaccinium vitis-idaea",
                           Logger_ID=="95221015"~"Vaccinium vitis-idaea",
                           TRUE~"N/A"))
```

```{r}
##Adds new column to data with TMS moisture formatted information
library(myClim)
data_Sogndal_complete <- open_data |>
# Create a new variable for TMS_moist, running the function 'calc_soil_moist'
# Check your column names for equivilent of 'Soilmoisture_raw', 'TMS_T1', and we can also just use 'silt_loam' so that can stay the same.
  mutate(TMS_moist = calc_soil_moist(rawsoilmoist = SoilMoist_Raw,
                                     soil_temp = Temp_1,
                                     soilclass ="silt_loam"))
```

```{r}
#This function is just experimental and gets the average temperatures for the entire time that the loggers were in place and across all logger data points for each habitat and species 
library(dplyr)
data_Sogndal_complete %>%
  group_by(species, habitat)%>%
  summarize(avg_temp1=mean(Temp_1, na.rm=TRUE), avg_temp2=mean(Temp_2, na.rm=TRUE), avg_temp3=mean(Temp_3, na.rm=TRUE))

```

```{r}
#this function helps reveal the fact that a few of the Loggers have some innacurate readings, reflecting high values year-round, probably due to the fact that they were kept in a lab and then replaced older loggers later on in the dataframe. Loggers 95221029, 95221192, and 95221194 are the culprits.
library(dplyr)
threshold_temp <- 20 #Picked number just as a general placemarker
data_Sogndal_analyzed <- data_Sogndal_complete %>%
  group_by(Logger_ID, date) %>%
  summarise(over_threshold = any(Temp_1 > threshold_temp)) %>%
  mutate(extremes_1 = cumsum(over_threshold))


```

```{r eval=FALSE}
#this function is just experimental and looks at the count of temps above the extreme 20 celsius over the course of a day, measuring not just if the extreme was met that day, but when/for how long.
library(dplyr)
threshold_temp <- 20
data_Sogndal_analyzed2 <- data_Sogndal_complete %>% 
  group_by(Logger_ID, date, time) %>%
  summarise(over_threshold = any(Temp_1 > threshold_temp)) %>%
  mutate(extremes_1 = cumsum(over_threshold))
```

```{r}
library(dplyr) #this function gets rid of the data included by the faulty loggers identified earlier
data_Sogndal_processed_old<- data_Sogndal_complete %>%
  filter(!Logger_ID %in% c("95221029", "95221192", "95221194"))
```

```{r}
####Isolates faulty logger data, creates graph to identify when they were replaced, and cuts out time before they were placed in the field.
data_Sogndal_faulty<- data_Sogndal_complete %>%
  group_by(date)%>% 
  filter(Logger_ID %in% c("95221029", "95221192", "95221194"))%>%

data_Sogndal_faulty_cut<- data_Sogndal_faulty%>%
  filter(date >= as.Date("2024-06-01"))

library(ggplot2)
ggplot(data_Sogndal_faulty, aes(x = date, y = Temp_1, color=Logger_ID)) +
  geom_line()
```

```{r}
##This function edits the data so that the faulty logger data is adjusted to just the timeframe when it is accurate 
library(dplyr)
data_Sogndal_processed <- data_Sogndal_complete %>%
  select (-SoilMoist_Raw)%>%
  filter(
    !(Logger_ID %in% c("95221029", "95221192", "95221194")) |
      (Logger_ID %in% c("95221029", "95221192", "95221194") & date >= as.Date("2024-06-01"))
  )
```

```{r}
##Function to save and export data table "data_Sogndal_processed" created above
write.csv(data_Sogndal_processed, "Sogndal_Logger_Data.csv", row.names=FALSE)
```

```{r}
##Separating data from Sogndal_processed into four different datasets so column numbers will fit in excel

data_Sogndal_EN<-data_Sogndal_processed %>%
  filter(species=="Empetrum nigrum")

data_Sogndal_CV<-data_Sogndal_processed %>%
  filter(species=="Calluna vulgaris")

data_Sogndal_VV<-data_Sogndal_processed %>%
  filter(species=="Vaccinium vitis-idaea")

data_Sogndal_VM<-data_Sogndal_processed %>%
  filter(species=="Vaccinium myrtillus")
```

```{r}
##Function to get newly divided Sogndal data into .csv file form
write.csv(data_Sogndal_EN, "Sogndal_Data_EN.csv", row.names=FALSE)
write.csv(data_Sogndal_CV, "Sogndal_Data_CV.csv", row.names=FALSE)
write.csv(data_Sogndal_VV, "Sogndal_Data_VV.csv", row.names=FALSE)
write.csv(data_Sogndal_VM, "Sogndal_Data_VM.csv", row.names=FALSE)
```

```{r}
library(dplyr)
#this function compares open v.s. forested and species measurements above the "extreme" values (20 celsius to -20 celcius at intervals of 5 degrees) for each day
count_extremes_by_day <- data_Sogndal_processed %>%
  group_by(date, habitat, species)%>%
  filter(Logger_ID!=95221022)%>% #This logger seemed to be giving some innacurate results (sustained temp leading to overcounting of some extreme values for Forest_Empetrum Nigrum) so removed it from the data for now (edit made as of 06/06/2025).
  summarize(
    Extreme_30=sum(Temp_3>30, na.rm=TRUE),
    Extreme_25=sum(Temp_3>25, na.rm=TRUE),
    Extreme_20=sum(Temp_3>20, na.rm=TRUE),
    Extreme_15=sum(Temp_3>15, na.rm=TRUE),
    Extreme_10=sum(Temp_3>10, na.rm=TRUE),
    Extreme_5=sum(Temp_3>5, na.rm=TRUE),
    Extreme_1=sum(Temp_3>1, na.rm=TRUE),
    Extreme_abv0=sum(Temp_3>0, na.rm=TRUE),
    Extreme_bel0=sum(Temp_3<0, na.rm=TRUE),
    Extreme_neg1=sum(Temp_3< -1, na.rm=TRUE),
    Extreme_neg5=sum(Temp_3< -5, na.rm=TRUE),
    Extreme_neg10=sum(Temp_3< -10, na.rm=TRUE),
    Extreme_neg15=sum(Temp_3< -15, na.rm=TRUE),
    Extreme_neg20=sum(Temp_3< -20, na.rm=TRUE))

#Earlier version of function that just counted measurements exceeding an extreme of 20 celsius
count_extremes_by_day2 <- data_Sogndal_processed %>%
    filter(Temp_3 >= 20) %>%      
    group_by(date, habitat, species) %>%
    summarise(extreme_count = n(), .groups = "drop")
```

```{r}
##This function looks at the number of extreme values, with separation for the land type and plant type
library(ggplot2)
library(dplyr)
count_extremes_edited <- count_extremes_by_day %>%
  mutate(Group = paste(habitat, species, sep = "_"))
```

```{r}
###The purpose of this code is to create a graph illustrating the counts of the different temperature extremes over time with respect to the habitat and species of the plant  
library(forcats)
long_extreme<-count_extremes_edited%>%
  pivot_longer (cols=c(Extreme_30, Extreme_25, Extreme_20, Extreme_15, Extreme_10, Extreme_5, Extreme_1, Extreme_abv0, Extreme_bel0, Extreme_neg1, Extreme_neg5, Extreme_neg10, Extreme_neg15, Extreme_neg20),
                names_to = "threshold",
                values_to = "count")


long_extreme %>% 
  mutate(threshold = factor(threshold)) %>%
 mutate(threshold = fct_relevel(threshold, 
                           c("Extreme_30", "Extreme_25", "Extreme_20", "Extreme_15","Extreme_10", "Extreme_5", "Extreme_1","Extreme_abv0",
                                      "Extreme_bel0","Extreme_neg1", "Extreme_neg5","Extreme_neg10","Extreme_neg15","Extreme_neg20")))

#long_extreme$threshold<- as.factor(as.character(long_extreme$threshold))



ggplot(long_extreme, aes(x = date, y = count, color = threshold)) +
  geom_line(size = 1) +
  labs(
    title = "Temperature Extremes Over Time by Species",
    x = "Date",
    y = "Extreme Count",
    color = "Temperature Threshold"
  ) +
  facet_wrap(~ Group) +
  theme_minimal()


long_extreme %>%
  filter(count == "")

ggplot(long_extreme, aes(x = date, y = count, color = Group)) +
  geom_line(size = 1) +
  labs(
    title = "Temperature Extremes Over Time by Species",
    x = "Date",
    y = "Extreme Count",
    color = "Temperature Threshold"
  ) +
  facet_wrap(~ threshold) +
  theme_minimal()
```

```{r}
##Creating graph similar to the one above but only with reagrds to the habitat as supossed to every habitat/species combination.

long_extreme<-count_extremes_edited%>%
  pivot_longer (cols=c(Extreme_30, Extreme_25, Extreme_20, Extreme_15, Extreme_10, Extreme_5, Extreme_1, Extreme_abv0, Extreme_bel0, Extreme_neg1, Extreme_neg5, Extreme_neg10, Extreme_neg15, Extreme_neg20),
                names_to = "threshold",
                values_to = "count")

ggplot(long_extreme, aes(x = date, y = count, color = habitat)) +
  geom_line(size = 1) +
  labs(
    title = "Temperature Extremes Over Time by Species",
    x = "Date",
    y = "Extreme Count",
    color = "Temperature Threshold"
  ) +
  facet_wrap(~ threshold) +
  theme_minimal()
```

```{r}
##Creating graph similar to the one above but only with regards to the species as supossed to habitat combination.

long_extreme<-count_extremes_edited%>%
  pivot_longer (cols=c(Extreme_30, Extreme_25, Extreme_20, Extreme_15, Extreme_10, Extreme_5, Extreme_1, Extreme_abv0, Extreme_bel0, Extreme_neg1, Extreme_neg5, Extreme_neg10, Extreme_neg15, Extreme_neg20),
                names_to = "threshold",
                values_to = "count")

ggplot(long_extreme, aes(x = date, y = count, color = species)) +
  geom_line(size = 1) +
  labs(
    title = "Temperature Extremes Over Time by Species",
    x = "Date",
    y = "Extreme Count",
    color = "Temperature Threshold"
  ) +
  facet_wrap(~ threshold) +
  theme_minimal()
```

```{r}
data_issues<-data_Sogndal_processed%>%
  filter(habitat=="Forest")%>%
  filter(species=="Empetrum nigrum")%>%
  filter(date>"2025-05-01")%>%
  filter(Temp_3>0)
```

```{r}
##Creates table showing a list of the maximum and minimum tempuratures divided by date, habitat, and species, along with the range, mean, and standard deviations for each of the three temperature readings (at different heights). 
library(dplyr)
Sogndal_analysis <- data_Sogndal_processed %>%
  group_by(date, habitat, species) %>%
  summarize (Daily_Max_1 = max(Temp_1, na.rm = TRUE),Daily_Min_1 = min(Temp_1, na.rm = TRUE), Mean_1=mean(Temp_1, na.rm=TRUE), Range_1=Daily_Max_1-Daily_Min_1, sd_1=sd(Temp_1), Daily_Max_2 = max(Temp_2, na.rm = TRUE),Daily_Min_2 = min(Temp_2, na.rm = TRUE),Mean_2=mean(Temp_2, na.rm=TRUE), Range_2=Daily_Max_2-Daily_Min_2, sd_2=sd(Temp_2), Daily_Max_3 = max(Temp_3, na.rm = TRUE),Daily_Min_3 = min(Temp_3, na.rm = TRUE), Mean_3=mean(Temp_3, na.rm=TRUE), Range_3=Daily_Max_3-Daily_Min_3, sd_3=sd(Temp_3))
```

```{r}
Sogndal_analysis_monthly_alt <- data_Sogndal_processed %>%
  mutate(Year = year(date),
         Month = month(date)) %>%
  group_by(Year, Month, habitat, species) %>%
  summarize (Mean_3=mean(Temp_3, na.rm=TRUE), sd_3=sd(Temp_3))%>%
  mutate(Group = paste(habitat, species, sep = "_"))%>%
  mutate(date = paste0(Year, "-", sprintf("%02d", Month)))%>%
  mutate(date=paste0(date, "-01")) %>%
  mutate(date = as.Date(date, format = "%Y-%m-%d"))
```

```{r}
##Creates analysis table with monthly analysis values instead of daily 
Sogndal_analysis_monthly_bad <- Sogndal_analysis %>%
  mutate(Year = year(date),
         Month = month(date)) %>%
  group_by(Year, Month, habitat, species) %>%
  summarize (Date=format(date, "%Y-%m"), Group=paste (habitat, species, sep = "_"), Monthly_Avg_Temp = mean(Mean_3, na.rm = TRUE), Monthly_Max_Temp = max(Mean_3), Monthly_Min_Temp = min(Mean_3), Monthly_Range_Temp = (Monthly_Max_Temp-Monthly_Min_Temp), Monthly_sd_Temp = sd(Mean_3)) %>%
  ungroup()

Sogndal_analysis_monthly<-Sogndal_analysis_monthly_bad %>%
  distinct()%>%
  select(-Year)%>%
  select(-Month)
```

```{r}
##Form a jittered line plot graph with error bars based on Sogndal monthly analysis values
pd<-position_dodge(0.5)
ggplot(Sogndal_analysis_monthly, aes(x=Date, y=Monthly_Avg_Temp, color=Group)) + 
  geom_line() +
  geom_point()+
  geom_jitter(position=pd) +
  geom_errorbar(aes(ymin=Monthly_Avg_Temp-Monthly_sd_Temp, ymax=Monthly_Avg_Temp+Monthly_sd_Temp), width=.5,
                 position=pd) +
  labs(title="Monthly Average Analysis", x="Date", y = "Temperature")
```

```{r}
###Version of the code that uses raw data to inform monthly averages instead of daily averages. Wasen't able to get jitter to work for some reason on this one though unfortunately:( 
pd<-position_dodge(0.5)
ggplot(Sogndal_analysis_monthly_alt, aes(x=date, y=Mean_3, color=Group)) +
  scale_x_date(date_labels = "%Y-%m", date_breaks = "1 month") +
  geom_point()+
  geom_jitter(position=pd) +
  geom_errorbar(aes(ymin=Mean_3-sd_3, ymax=Mean_3+sd_3), width=.5,
                 position=pd) +
  labs(title="Monthly Average Analysis", x="Date", y = "Temperature")
```
